# Connection Pool, javax.mail
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      username: GD
      password: 1111
  web:
    resources:
      static-locations:
      - classpath:/static/css/
      - classpath:/static/js/
      - classpath:/static/image/

#  main:
#    web-application-type: none  # Do not use embeded tomcat

# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml

# character encoding, session, port
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
  port: 8080